FROM python:3.12-slim AS builder

RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

# install CRKIT
RUN mkdir /opt/crkit && \
        cd /opt/crkit && \
        wget http://crl.med.harvard.edu/CRKIT/CRKIT-1.6.0-RHEL6.tar.gz && \
        tar -xf CRKIT-1.6.0-RHEL6.tar.gz crkit-1.6.0/bin/crlRigidRegistration crkit-1.6.0/Frameworks/InsightToolkit && \
        rm CRKIT-1.6.0-RHEL6.tar.gz

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# add env variables
ENV BUNDLE /opt/crkit/crkit-1.6.0
ENV PATH $PATH:$BUNDLE/bin
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$BUNDLE/itk-4.6.1/lib
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$BUNDLE/Frameworks/InsightToolkit:$BUNDLE/Frameworks/vtk-6.1:$BUNDLE/Frameworks/qt-5.3.2/lib:$BUNDLE/lib:$BUNDLE/bin
ENV QT_PLUGIN_PATH $BUNDLE/Frameworks/qt-5.3.2/plugins
ENV DYLD_LIBRARY_PATH ""

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_TYPE=en_US.UTF-8

# install GGR-recon
RUN mkdir -p /opt/GGR-recon
COPY utils.py /opt/GGR-recon
COPY preprocess.py /opt/GGR-recon
COPY recon.py /opt/GGR-recon
ENV PATH ${PATH}:/opt/GGR-recon
RUN chmod a+rx /opt/GGR-recon/preprocess.py
RUN chmod a+rx /opt/GGR-recon/recon.py

WORKDIR /opt/GGR-recon

# DEFAULT CMD provides a list of programs.
ENV msg="\nRun one of these programs:\n"
CMD echo $msg; find /opt/GGR-recon/ -type f -name "*.py"; echo $msg
