name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set current date
      id: date
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag crl/ggr-recon:${{ steps.date.outputs.NOW }}
        docker save crl/ggr-recon:${{ steps.date.outputs.NOW }} -o crl-ggr-recon-${{ steps.date.outputs.NOW }}.tar
        

    - uses: actions/upload-artifact@v4
      with:
        name: crl-ggr-recon-container
        path: crl-ggr-recon-${{ steps.date.outputs.NOW }}.tar
