name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set current date
      id: date
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ggr-recon:${{ steps.date.outputs.NOW }}
        docker save ggr-recon:${{ steps.date.outputs.NOW }} -o ggr-recon-${{ steps.date.outputs.NOW }}.tar
        docker tag ggr-recon:${{ steps.date.outputs.NOW }} ggr-recon:latest
        docker build ggr-gear --file ggr-gear/Dockerfile --tag ggr-recon-gear:${{ steps.date.outputs.NOW }}
        docker save ggr-recon-gear:${{ steps.date.outputs.NOW }} -o ggr-recon-gear:${{ steps.date.outputs.NOW }}.tar
      
    - uses: actions/upload-artifact@v3
      with:
        name: ggr-recon-container
        path: ggr-recon-${{ steps.date.outputs.NOW }}.tar
        
    - uses: actions/upload-artifact@v3
      with:
        name: ggr-recon-gear-container
        path: ggr-recon-gear-${{ steps.date.outputs.NOW }}.tar
