name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set current date
      id: date
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ggr-recon:${NOW}
        docker save ggr-recon:${NOW} -o ggr-recon-${NOW}.tar
      
    - uses: actions/upload-artifact@v3
      with:
        name: ggr-recon-container
        path: ggr-recon-${NOW}.tar
